# Generated by Django 4.2.4 on 2023-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.ManyToManyField(null=True, to='tweet.tweeetfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tweet_txt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.ManyToManyField(null=True, to='tweet.tweeetfile'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_txt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
