# Generated by Django 4.2.4 on 2023-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_comment_likes_alter_comment_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comments',
            field=models.ManyToManyField(null=True, to='tweet.comment'),
        ),
    ]
