# Generated by Django 4.2.4 on 2023-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeetfile',
            name='type',
            field=models.CharField(default='img', max_length=5),
        ),
    ]
