# Generated by Django 4.2.4 on 2023-09-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_profile_pics'),
        ('tweet', '0005_remove_comment_likes_remove_tweet_likes_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='profile',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
            preserve_default=False,
        ),
    ]
