# Generated by Django 4.2.4 on 2023-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_like_tweetid_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(null=True, to='tweet.comment'),
        ),
    ]
